In [1]:
import pandas as pd
daily_data = pd.read_csv('../data/processed/onion_cleaned.csv', parse_dates=['Arrival_Date'])
daily_data = daily_data.sort_values(['Market', 'Arrival_Date']).reset_index(drop=True)

## **Lag Features**

In [2]:
daily_data['Price_Lag_1'] = (daily_data.groupby('Market')['Modal_Price'].shift(1))
daily_data['Price_Lag_7'] = (daily_data.groupby('Market')['Modal_Price'].shift(7))
daily_data['Price_Lag_30'] = (daily_data.groupby('Market')['Modal_Price'].shift(30))

In [3]:
daily_data.head(10)

,Market,Arrival_Date,Commodity_Code,Max_Price,Min_Price,Modal_Price,Rolling_Median,Price_Ratio,Next_Price,Next_Rolling_Median,Next_Price_Ratio,Likely_Error,Price_Lag_1,Price_Lag_7,Price_Lag_30
0,Chandvad,2003-01-30,23.0,155.0,90.0,130.0,NaN,NaN,110.0,NaN,NaN,False,NaN,NaN,NaN
1,Chandvad,2003-02-06,23.0,130.0,60.0,110.0,NaN,NaN,135.0,130.0,1.038462,False,130.0,NaN,NaN
2,Chandvad,2003-02-07,23.0,155.0,60.0,135.0,130.0,1.038462,125.0,127.5,0.980392,False,110.0,NaN,NaN
3,Chandvad,2003-02-13,23.0,207.0,80.0,125.0,127.5,0.980392,130.0,130.0,1.000000,False,135.0,NaN,NaN
4,Chandvad,2003-02-15,23.0,191.0,60.0,130.0,130.0,1.000000,130.0,130.0,1.000000,False,125.0,NaN,NaN
5,Chandvad,2003-02-18,23.0,165.0,70.0,130.0,130.0,1.000000,140.0,130.0,1.076923,False,130.0,NaN,NaN
6,Chandvad,2003-02-19,23.0,165.0,120.0,140.0,130.0,1.076923,151.0,130.0,1.161538,False,130.0,NaN,NaN
7,Chandvad,2003-02-20,23.0,175.0,125.0,151.0,130.0,1.161538,165.0,135.0,1.222222,False,140.0,130.0,NaN
8,Chandvad,2003-02-21,23.0,190.0,120.0,165.0,135.0,1.222222,175.0,140.0,1.250000,False,151.0,110.0,NaN
9,Chandvad,2003-02-22,23.0,201.0,125.0,175.0,140.0,1.250000,160.0,151.0,1.059603,False,165.0,135.0,NaN

## **Rolling averages**

In [4]:
daily_data['Rolling_Mean_7'] = (
    daily_data
    .groupby('Market')['Modal_Price']
    .transform(lambda x: x.shift(1).rolling(window=7).mean())
)

daily_data['Rolling_Mean_30'] = (
    daily_data
    .groupby('Market')['Modal_Price']
    .transform(lambda x: x.shift(1).rolling(window=30).mean())
)

In [5]:
daily_data.head(10)

,Market,Arrival_Date,Commodity_Code,Max_Price,Min_Price,Modal_Price,Rolling_Median,Price_Ratio,Next_Price,Next_Rolling_Median,Next_Price_Ratio,Likely_Error,Price_Lag_1,Price_Lag_7,Price_Lag_30,Rolling_Mean_7,Rolling_Mean_30
0,Chandvad,2003-01-30,23.0,155.0,90.0,130.0,NaN,NaN,110.0,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN
1,Chandvad,2003-02-06,23.0,130.0,60.0,110.0,NaN,NaN,135.0,130.0,1.038462,False,130.0,NaN,NaN,NaN,NaN
2,Chandvad,2003-02-07,23.0,155.0,60.0,135.0,130.0,1.038462,125.0,127.5,0.980392,False,110.0,NaN,NaN,NaN,NaN
3,Chandvad,2003-02-13,23.0,207.0,80.0,125.0,127.5,0.980392,130.0,130.0,1.000000,False,135.0,NaN,NaN,NaN,NaN
4,Chandvad,2003-02-15,23.0,191.0,60.0,130.0,130.0,1.000000,130.0,130.0,1.000000,False,125.0,NaN,NaN,NaN,NaN
5,Chandvad,2003-02-18,23.0,165.0,70.0,130.0,130.0,1.000000,140.0,130.0,1.076923,False,130.0,NaN,NaN,NaN,NaN
6,Chandvad,2003-02-19,23.0,165.0,120.0,140.0,130.0,1.076923,151.0,130.0,1.161538,False,130.0,NaN,NaN,NaN,NaN
7,Chandvad,2003-02-20,23.0,175.0,125.0,151.0,130.0,1.161538,165.0,135.0,1.222222,False,140.0,130.0,NaN,128.571429,NaN
8,Chandvad,2003-02-21,23.0,190.0,120.0,165.0,135.0,1.222222,175.0,140.0,1.250000,False,151.0,110.0,NaN,131.571429,NaN
9,Chandvad,2003-02-22,23.0,201.0,125.0,175.0,140.0,1.250000,160.0,151.0,1.059603,False,165.0,135.0,NaN,139.428571,NaN

## **seasonal indicator**

In [6]:
daily_data['Month'] = daily_data['Arrival_Date'].dt.month

## **cross-market average price**

In [7]:
market_avg_by_date = daily_data.groupby('Arrival_Date')['Modal_Price'].transform('mean')

In [8]:
daily_data['Cross_Market_Avg'] = daily_data.groupby('Arrival_Date')['Modal_Price'].transform('mean')

In [9]:
daily_data.isna().sum()

Market                   0
Arrival_Date             0
Commodity_Code           0
Max_Price                0
Min_Price                0
Modal_Price              0
Rolling_Median          16
Price_Ratio             16
Next_Price               8
Next_Rolling_Median     16
Next_Price_Ratio        16
Likely_Error             0
Price_Lag_1              8
Price_Lag_7             56
Price_Lag_30           240
Rolling_Mean_7          56
Rolling_Mean_30        240
Month                    0
Cross_Market_Avg         0
dtype: int64

#### **Clean up leftover columns you don't need anymore**

In [10]:
daily_data = daily_data.drop(columns=['Rolling_Median','Price_Ratio','Next_Price','Next_Rolling_Median','Next_Price_Ratio','Likely_Error'])

#### **dropping rows with NaN in actual feature columns**

In [11]:
model_data = daily_data.dropna().reset_index(drop=True)
print(model_data.shape)

(33895, 13)

In [12]:
model_data.to_csv('../data/processed/onion_model_ready.csv', index=False)